services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    container_name: paper
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.4"
      VIEW_DISTANCE: 10
      MEMORY: 4G
    ports:
      - "25565:25565"
      - "8123:8123"
    volumes:
      - ./mcserver-data:/data
    restart: unless-stopped
  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.15
    container_name: playit
    network_mode: host
    environment:
    - SECRET_KEY=${PLAYIT_SECRET_KEY}
    restart: unless-stopped
